-- Create the probes table in Supabase
create table public.probes (
  id bigint generated by default as identity primary key,
  text text not null,
  name text not null default 'Anonymous',
  status text not null default 'pending' check (status in ('pending', 'approved', 'rejected')),
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now()
);

-- Enable Row Level Security
alter table public.probes enable row level security;

-- Allow public to insert new probes
create policy "Anyone can insert probes" on public.probes
  for insert with check (true);

-- Allow public to read approved probes
create policy "Anyone can read approved probes" on public.probes
  for select using (status = 'approved');

-- Allow reading all probes for admin (you'll implement auth later)
create policy "Allow admin to read all probes" on public.probes
  for select using (true);

-- Allow admin to update probe status
create policy "Allow admin to update probes" on public.probes
  for update using (true);

-- Allow admin to delete probes  
create policy "Allow admin to delete probes" on public.probes
  for delete using (true);

-- Insert some sample approved probes
insert into public.probes (text, name, status, created_at) values
  ('Why do we seek certainty in a universe that seems fundamentally uncertain?', 'Sarah M.', 'approved', '2026-03-02 10:00:00+00'),
  ('What if our greatest innovations come from the courage to stand alone with an unpopular truth?', 'Anonymous', 'approved', '2026-02-25 15:30:00+00'),
  ('Is questioning everything just another form of certainty?', 'Michael R.', 'approved', '2026-02-12 09:15:00+00');

-- Create updated_at trigger
create or replace function public.handle_updated_at()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

create trigger handle_probes_updated_at
  before update on public.probes
  for each row
  execute function public.handle_updated_at();